server:
  port: 80

spring:
  datasource:                # 数据源相关配置  localhost改成云服务器内网ip
    url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456