###########################################################
#
#     内置Tomcat web访问端口号  约定：8088   如端口被占用 lsof -i tcp:8088    kill ***
#
###########################################################
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

###########################################################
#
#     配置数据源信息
#
###########################################################
spring:
  datasource:                                             # 数据源相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000          # 等待连接池分配连接的最大时长（毫秒），超过时长还没有可用连接则发生SQLException，默认30秒
      minimum-idle: 5                    # 最小连接数
      maximum-pool-size: 20              # 最大连接数
      auto-commit: true                  # 自动提交
      idle-timeout: 600000               # 连接超时的最大时长（毫秒），超市则被释放（retired）,默认 10分钟
      pool-name: DataSourceHikariCP      # 连接池名字
      max-lifetime: 1800000              # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired）默认 30分钟1800000ms
      connection-test-query: SELECT 1    # 连接时测试的SQL语句
  servlet:
    multipart:
      max-file-size: 512000 # 文件上传大小为500kb
      max-request-size: 512000 # 请求大小限制为500kb
###########################################################
#
#     mybatis 配置
#
###########################################################
mybatis:
  type-aliases-package: com.imooc.pojo          # 所有POJO类所在包路径 实体类映射
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 在控制台输出SQL语句(开发环境使用)


###########################################################
#
#     mybatis mapper 配置
#
###########################################################
# 通用Mapper 配置(tk.mybatis)
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false   # 在进行数据库操作时，判断表达式 username != null 时，是否追加username != ''
  identituy: MYSQL




